name: Test Demo React App
on:
  push:
    branches: [ master ]
jobs:
  build-and-test-dashboard:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./example-3-production-app
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run prettier
    - run: npm run typecheck
    - run: npm run build
